---
abstract: 'This module is a simple SQL file loader'
author:
  - 'Lucas Tiago de Moraes <lucastiagodemoraes@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: SQL-Load
no_index:
  directory:
    - t
    - inc
requires:
  Carp: '0'
  Exporter: '0'
  String::CamelCase: '0.04'
  base: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/ltmbr/SQL-Load/issues
  homepage: https://github.com/ltmbr/SQL-Load
  repository: https://github.com/ltmbr/SQL-Load
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
